// Generated by VM Code Writer written by Silas Kraume


// function Main.main 1
(Main.main)
    @SP // Initialize local variable 0
    A=M
    M=0
    @SP
    M=M+1

// push pointer 0
    @0
    D=A
    @THIS
    A=D+A
    D=M
    @SP
    A=M
    M=D
    @SP
    M=M+1

// push constant 3
    @3
    D=A
    @SP
    A=M
    M=D
    @SP
    M=M+1

// push constant 4
    @4
    D=A
    @SP
    A=M
    M=D
    @SP
    M=M+1

// call Main.ackermann 3
    @RETURN_Main.ackermann_0 // save return address
    D=A
    @SP
    A=M
    M=D
    @SP
    M=M+1

    @LCL // save @LCL segment
    D=M
    @SP
    A=M
    M=D
    @SP
    M=M+1

    @ARG // save @ARG segment
    D=M
    @SP
    A=M
    M=D
    @SP
    M=M+1

    @THIS // save @THIS segment
    D=M
    @SP
    A=M
    M=D
    @SP
    M=M+1

    @THAT // save @THAT segment
    D=M
    @SP
    A=M
    M=D
    @SP
    M=M+1

    @8 // reposition ARG to SP - numArgs - 5
    D=A
    @SP
    D=M-D
    @ARG
    M=D

    @SP // reposition LCL to SP
    D=M
    @LCL
    M=D

    @Main.ackermann // transfer control to function
    0;JMP
(RETURN_Main.ackermann_0)

// pop local 0
    @0
    D=A
    @LCL
    D=D+M
    @R13
    M=D
    @SP
    AM=M-1
    D=M
    @R13
    A=M
    M=D

// function Main.ackermann 0
(Main.ackermann)
// push argument 0
    @0
    D=A
    @ARG
    A=D+M
    D=M
    @SP
    A=M
    M=D
    @SP
    M=M+1

// push constant 0
    @0
    D=A
    @SP
    A=M
    M=D
    @SP
    M=M+1

// eq
    @SP
    AM=M-1
    D=M
    A=A-1
    M=M-D
    D=M
    @COMPARISON1
    D;JEQ
    @SP
    A=M-1
    M=0
    @ENDCOMPARISON1
    0;JMP
(COMPARISON1)
    @SP
    A=M-1
    M=-1
(ENDCOMPARISON1)
    
// not
    @SP
    A=M-1
    M=!M
    
// if-goto Main.ackermann.LABEL_0
    @SP
    AM=M-1
    D=M
    @Main.ackermann$Main.ackermann.LABEL_0
    D;JNE

// push argument 1
    @1
    D=A
    @ARG
    A=D+M
    D=M
    @SP
    A=M
    M=D
    @SP
    M=M+1

// push constant 1
    @1
    D=A
    @SP
    A=M
    M=D
    @SP
    M=M+1

// add
    @SP
    AM=M-1
    D=M
    A=A-1
    M=D+M
    
// return
    @LCL // save LCL in R13
    D=M
    @R13
    M=D

    @5 // save return address in R14
    A=D-A
    D=M
    @R14
    M=D

    @SP // reposition return value for caller
    AM=M-1
    D=M
    @ARG
    A=M
    M=D

    @ARG // restore SP for caller
    D=M+1
    @SP
    M=D

    @R13 // restore @THAT segment
    AM=M-1
    D=M
    @THAT
    M=D

    @R13 // restore @THIS segment
    AM=M-1
    D=M
    @THIS
    M=D

    @R13 // restore @ARG segment
    AM=M-1
    D=M
    @ARG
    M=D

    @R13 // restore @LCL segment
    AM=M-1
    D=M
    @LCL
    M=D

    @R14 // return to caller
    A=M
    0;JMP

// goto Main.ackermann.LABEL_1
    @Main.ackermann$Main.ackermann.LABEL_1
    0;JMP

// label Main.ackermann.LABEL_0
(Main.ackermann$Main.ackermann.LABEL_0)

// label Main.ackermann.LABEL_1
(Main.ackermann$Main.ackermann.LABEL_1)

// push argument 1
    @1
    D=A
    @ARG
    A=D+M
    D=M
    @SP
    A=M
    M=D
    @SP
    M=M+1

// push constant 0
    @0
    D=A
    @SP
    A=M
    M=D
    @SP
    M=M+1

// eq
    @SP
    AM=M-1
    D=M
    A=A-1
    M=M-D
    D=M
    @COMPARISON2
    D;JEQ
    @SP
    A=M-1
    M=0
    @ENDCOMPARISON2
    0;JMP
(COMPARISON2)
    @SP
    A=M-1
    M=-1
(ENDCOMPARISON2)
    
// not
    @SP
    A=M-1
    M=!M
    
// if-goto Main.ackermann.LABEL_2
    @SP
    AM=M-1
    D=M
    @Main.ackermann$Main.ackermann.LABEL_2
    D;JNE

// push pointer 0
    @0
    D=A
    @THIS
    A=D+A
    D=M
    @SP
    A=M
    M=D
    @SP
    M=M+1

// push argument 0
    @0
    D=A
    @ARG
    A=D+M
    D=M
    @SP
    A=M
    M=D
    @SP
    M=M+1

// push constant 1
    @1
    D=A
    @SP
    A=M
    M=D
    @SP
    M=M+1

// sub
    @SP
    AM=M-1
    D=M
    A=A-1
    M=M-D
    
// push constant 1
    @1
    D=A
    @SP
    A=M
    M=D
    @SP
    M=M+1

// call Main.ackermann 3
    @RETURN_Main.ackermann_3 // save return address
    D=A
    @SP
    A=M
    M=D
    @SP
    M=M+1

    @LCL // save @LCL segment
    D=M
    @SP
    A=M
    M=D
    @SP
    M=M+1

    @ARG // save @ARG segment
    D=M
    @SP
    A=M
    M=D
    @SP
    M=M+1

    @THIS // save @THIS segment
    D=M
    @SP
    A=M
    M=D
    @SP
    M=M+1

    @THAT // save @THAT segment
    D=M
    @SP
    A=M
    M=D
    @SP
    M=M+1

    @8 // reposition ARG to SP - numArgs - 5
    D=A
    @SP
    D=M-D
    @ARG
    M=D

    @SP // reposition LCL to SP
    D=M
    @LCL
    M=D

    @Main.ackermann // transfer control to function
    0;JMP
(RETURN_Main.ackermann_3)

// return
    @LCL // save LCL in R13
    D=M
    @R13
    M=D

    @5 // save return address in R14
    A=D-A
    D=M
    @R14
    M=D

    @SP // reposition return value for caller
    AM=M-1
    D=M
    @ARG
    A=M
    M=D

    @ARG // restore SP for caller
    D=M+1
    @SP
    M=D

    @R13 // restore @THAT segment
    AM=M-1
    D=M
    @THAT
    M=D

    @R13 // restore @THIS segment
    AM=M-1
    D=M
    @THIS
    M=D

    @R13 // restore @ARG segment
    AM=M-1
    D=M
    @ARG
    M=D

    @R13 // restore @LCL segment
    AM=M-1
    D=M
    @LCL
    M=D

    @R14 // return to caller
    A=M
    0;JMP

// goto Main.ackermann.LABEL_3
    @Main.ackermann$Main.ackermann.LABEL_3
    0;JMP

// label Main.ackermann.LABEL_2
(Main.ackermann$Main.ackermann.LABEL_2)

// label Main.ackermann.LABEL_3
(Main.ackermann$Main.ackermann.LABEL_3)

// push pointer 0
    @0
    D=A
    @THIS
    A=D+A
    D=M
    @SP
    A=M
    M=D
    @SP
    M=M+1

// push argument 0
    @0
    D=A
    @ARG
    A=D+M
    D=M
    @SP
    A=M
    M=D
    @SP
    M=M+1

// push constant 1
    @1
    D=A
    @SP
    A=M
    M=D
    @SP
    M=M+1

// sub
    @SP
    AM=M-1
    D=M
    A=A-1
    M=M-D
    
// push pointer 0
    @0
    D=A
    @THIS
    A=D+A
    D=M
    @SP
    A=M
    M=D
    @SP
    M=M+1

// push argument 0
    @0
    D=A
    @ARG
    A=D+M
    D=M
    @SP
    A=M
    M=D
    @SP
    M=M+1

// push argument 1
    @1
    D=A
    @ARG
    A=D+M
    D=M
    @SP
    A=M
    M=D
    @SP
    M=M+1

// push constant 1
    @1
    D=A
    @SP
    A=M
    M=D
    @SP
    M=M+1

// sub
    @SP
    AM=M-1
    D=M
    A=A-1
    M=M-D
    
// call Main.ackermann 3
    @RETURN_Main.ackermann_4 // save return address
    D=A
    @SP
    A=M
    M=D
    @SP
    M=M+1

    @LCL // save @LCL segment
    D=M
    @SP
    A=M
    M=D
    @SP
    M=M+1

    @ARG // save @ARG segment
    D=M
    @SP
    A=M
    M=D
    @SP
    M=M+1

    @THIS // save @THIS segment
    D=M
    @SP
    A=M
    M=D
    @SP
    M=M+1

    @THAT // save @THAT segment
    D=M
    @SP
    A=M
    M=D
    @SP
    M=M+1

    @8 // reposition ARG to SP - numArgs - 5
    D=A
    @SP
    D=M-D
    @ARG
    M=D

    @SP // reposition LCL to SP
    D=M
    @LCL
    M=D

    @Main.ackermann // transfer control to function
    0;JMP
(RETURN_Main.ackermann_4)

// call Main.ackermann 3
    @RETURN_Main.ackermann_5 // save return address
    D=A
    @SP
    A=M
    M=D
    @SP
    M=M+1

    @LCL // save @LCL segment
    D=M
    @SP
    A=M
    M=D
    @SP
    M=M+1

    @ARG // save @ARG segment
    D=M
    @SP
    A=M
    M=D
    @SP
    M=M+1

    @THIS // save @THIS segment
    D=M
    @SP
    A=M
    M=D
    @SP
    M=M+1

    @THAT // save @THAT segment
    D=M
    @SP
    A=M
    M=D
    @SP
    M=M+1

    @8 // reposition ARG to SP - numArgs - 5
    D=A
    @SP
    D=M-D
    @ARG
    M=D

    @SP // reposition LCL to SP
    D=M
    @LCL
    M=D

    @Main.ackermann // transfer control to function
    0;JMP
(RETURN_Main.ackermann_5)

// return
    @LCL // save LCL in R13
    D=M
    @R13
    M=D

    @5 // save return address in R14
    A=D-A
    D=M
    @R14
    M=D

    @SP // reposition return value for caller
    AM=M-1
    D=M
    @ARG
    A=M
    M=D

    @ARG // restore SP for caller
    D=M+1
    @SP
    M=D

    @R13 // restore @THAT segment
    AM=M-1
    D=M
    @THAT
    M=D

    @R13 // restore @THIS segment
    AM=M-1
    D=M
    @THIS
    M=D

    @R13 // restore @ARG segment
    AM=M-1
    D=M
    @ARG
    M=D

    @R13 // restore @LCL segment
    AM=M-1
    D=M
    @LCL
    M=D

    @R14 // return to caller
    A=M
    0;JMP

