
class VMCodeWriter:
    def __init__(self, out_file: str) -> None:
        self.out_file = out_file
        self.f_out = open(self.out_file, 'w', encoding='utf-8')
        self.writeAssembly('// Generated by VM Code Writer written by Silas Kraume\n\n')

        self.label_id = 0
        self.c_file = ''

    def writeAssembly(self, line: str) -> None:
        if not (line.startswith('//') or line.startswith('(')):
            self.f_out.write('    ')
        self.f_out.write(f"{line}\n")

    def setCurrentFileName(self, file_name: str) -> None:
        self.c_file = file_name.replace('/', '_').replace('\\', '_')

    def __del__(self):
        if hasattr(self, 'f_out') and not self.f_out.closed:
            self.f_out.close()




    def writeInit(self) -> None:
        """
        Write the assembly code to initialize the VM.
        This is typically called at the start of the program.
        """
        self.writeAssembly('// init')
        self.writeAssembly('@256')
        self.writeAssembly('D=A')
        self.writeAssembly('@SP')
        self.writeAssembly('M=D')
        self.writeCall(0, 'Sys.init', 0)

    def writeArithmetic(self, _: int, command: str) -> None:
        """
        Write the assembly code for the arithmetic command.
        """
        self.writeAssembly(f"// {command}")

        if command not in ['neg', 'not']:
            self.writeAssembly('@SP')
            self.writeAssembly('AM=M-1')
            self.writeAssembly('D=M')
            self.writeAssembly('A=A-1')
        if command == 'add':
            self.writeAssembly('M=D+M')
        if command in ['sub', 'eq', 'gt', 'lt']:
            self.writeAssembly('M=M-D')
        if command == 'and':
            self.writeAssembly('M=D&M')
        if command == 'or':
            self.writeAssembly('M=D|M')

        if command in ['neg', 'not']:
            self.writeAssembly('@SP')
            self.writeAssembly('A=M-1')
        if command == 'neg':
            self.writeAssembly('M=-M')
        if command == 'not':
            self.writeAssembly('M=!M')

        if command in ['eq', 'gt', 'lt']:
            label_compare = f"COMPARISON{self.label_id}"
            label_compare_end = f"ENDCOMPARISON{self.label_id}"
            self.label_id += 1
            self.writeAssembly('D=M')

            self.writeAssembly(f"@{label_compare}")
            if command == 'eq':
                self.writeAssembly('D;JEQ')
            if command == 'gt':
                self.writeAssembly('D;JGT')
            if command == 'lt':
                self.writeAssembly('D;JLT')

            self.writeAssembly('@SP')
            self.writeAssembly('A=M-1')
            self.writeAssembly('M=0')
            self.writeAssembly(f"@{label_compare_end}")
            self.writeAssembly('0;JMP')

            self.writeAssembly(f"({label_compare})")
            self.writeAssembly('@SP')
            self.writeAssembly('A=M-1')
            self.writeAssembly('M=-1')

            self.writeAssembly(f"({label_compare_end})")

    def writePushPop(self, line: int, command: str, segment: str, index: int) -> None:
        """
        Write the assembly code for the push/pop command.
        """
        if command == 'C_PUSH':
            if segment not in [
                'constant',
                'local', 'argument', 'this', 'that', 'static', 'temp', 'pointer'
            ]:
                raise SyntaxError(f"Unknown segment for push: '{segment}' at line {line}")

            self.writeAssembly(f"// push {segment} {index}")
            if segment == 'static':
                self.writeAssembly(f"@{self.c_file}.{index}")
            elif segment == 'temp':
                self.writeAssembly(f"@{index + 5}")
            else:
                self.writeAssembly(f"@{index}")
            if segment not in ['static', 'temp']:
                self.writeAssembly('D=A')

            if segment == 'local':
                self.writeAssembly('@LCL')
            if segment == 'argument':
                self.writeAssembly('@ARG')
            if segment in ['this', 'pointer']:
                self.writeAssembly('@THIS')
            if segment == 'that':
                self.writeAssembly('@THAT')
            if segment in ['local', 'argument', 'this', 'that']:
                self.writeAssembly('A=D+M')
            if segment == 'pointer':
                self.writeAssembly('A=D+A')
            if segment != 'constant':
                self.writeAssembly('D=M')

            self.writeAssembly('@SP')
            self.writeAssembly('A=M')
            self.writeAssembly('M=D')
            self.writeAssembly('@SP')
            self.writeAssembly('M=M+1\n')

        if command == 'C_POP':
            if segment not in [
                'local', 'argument', 'this', 'that', 'static', 'temp', 'pointer'
            ]:
                raise SyntaxError(f"Unknown segment for push: '{segment}' at line {line}")

            self.writeAssembly(f"// pop {segment} {index}")
            if segment == 'static':
                self.writeAssembly(f"@{self.c_file}.{index}")
            elif segment == 'temp':
                self.writeAssembly(f"@{index + 5}")
            else:
                self.writeAssembly(f"@{index}")

            self.writeAssembly('D=A')

            if segment == 'local':
                self.writeAssembly('@LCL')
            if segment == 'argument':
                self.writeAssembly('@ARG')
            if segment in ['this', 'pointer']:
                self.writeAssembly('@THIS')
            if segment == 'that':
                self.writeAssembly('@THAT')
            if segment not in ['static', 'temp', 'pointer']:
                self.writeAssembly('D=D+M')
            if segment == 'pointer':
                self.writeAssembly('D=D+A')

            self.writeAssembly('@R13')
            self.writeAssembly('M=D')
            self.writeAssembly('@SP')
            self.writeAssembly('AM=M-1')
            self.writeAssembly('D=M')
            self.writeAssembly('@R13')
            self.writeAssembly('A=M')
            self.writeAssembly('M=D\n')

    def writeLabel(self, _: int, label: str) -> None:
        self.writeAssembly(f"// label {label}")
        self.writeAssembly(f"({label})\n")

    def writeGoto(self, _: int, label: str) -> None:
        self.writeAssembly(f"// goto {label}")
        self.writeAssembly(f"@{label}")
        self.writeAssembly('0;JMP\n')

    def writeIf(self, _: int, label: str) -> None:
        self.writeAssembly(f"// if-goto {label}")
        self.writeAssembly('@SP')
        self.writeAssembly('AM=M-1')
        self.writeAssembly('D=M')
        self.writeAssembly(f"@{label}")
        self.writeAssembly('D;JNE\n')

    def writeFunction(self, _: int, functionName: str, numLocals: int) -> None:
        self.writeAssembly(f"// function {functionName} {numLocals}")
        self.writeAssembly(f"({functionName})")

        for _ in range(numLocals):
            self.writeAssembly('@SP')
            self.writeAssembly('A=M')
            self.writeAssembly('M=0')
            self.writeAssembly('@SP')
            self.writeAssembly('M=M+1')

    def writeCall(self, _: int, functionName: str, numArgs: int) -> None:
        self.writeAssembly(f"// call {functionName} {numArgs}")

        return_label = f"RETURN_{functionName}_{self.label_id}"
        self.label_id += 1
        self.writeAssembly(f"@{return_label}")
        self.writeAssembly('D=A')
        self.writeAssembly('@SP')
        self.writeAssembly('A=M')
        self.writeAssembly('M=D')
        self.writeAssembly('@SP')
        self.writeAssembly('M=M+1\n')

        self.writeAssembly('@LCL')
        self.writeAssembly('D=M')
        self.writeAssembly('@SP')
        self.writeAssembly('A=M')
        self.writeAssembly('M=D')
        self.writeAssembly('@SP')
        self.writeAssembly('M=M+1\n')

        self.writeAssembly('@ARG')
        self.writeAssembly('D=M')
        self.writeAssembly('@SP')
        self.writeAssembly('A=M')
        self.writeAssembly('M=D')
        self.writeAssembly('@SP')
        self.writeAssembly('M=M+1\n')

        self.writeAssembly('@THIS')
        self.writeAssembly('D=M')
        self.writeAssembly('@SP')
        self.writeAssembly('A=M')
        self.writeAssembly('M=D')
        self.writeAssembly('@SP')
        self.writeAssembly('M=M+1\n')

        self.writeAssembly('@THAT')
        self.writeAssembly('D=M')
        self.writeAssembly('@SP')
        self.writeAssembly('A=M')
        self.writeAssembly('M=D')
        self.writeAssembly('@SP')
        self.writeAssembly('M=M+1\n')

        self.writeAssembly(f"@{numArgs + 5}")
        self.writeAssembly('D=A')
        self.writeAssembly('@SP')
        self.writeAssembly('D=M-D')
        self.writeAssembly('@ARG')
        self.writeAssembly('M=D\n')

        self.writeAssembly('@SP')
        self.writeAssembly('D=M')
        self.writeAssembly('@LCL')
        self.writeAssembly('M=D\n')

        self.writeAssembly(f"@{functionName}")
        self.writeAssembly('0;JMP')
        self.writeAssembly(f"({return_label})\n")

    def writeReturn(self, _: int) -> None:
        self.writeAssembly('// return')

        self.writeAssembly('@LCL')
        self.writeAssembly('D=M')
        self.writeAssembly('@R13')
        self.writeAssembly('M=D\n')

        self.writeAssembly('@5')
        self.writeAssembly('A=D-A')
        self.writeAssembly('D=M')
        self.writeAssembly('@R14')
        self.writeAssembly('M=D\n')

        self.writeAssembly('@SP')
        self.writeAssembly('AM=M-1')
        self.writeAssembly('D=M')
        self.writeAssembly('@ARG')
        self.writeAssembly('A=M')
        self.writeAssembly('M=D\n')

        self.writeAssembly('@ARG')
        self.writeAssembly('D=M+1')
        self.writeAssembly('@SP')
        self.writeAssembly('M=D\n')

        self.writeAssembly('@R13')
        self.writeAssembly('AM=M-1')
        self.writeAssembly('D=M')
        self.writeAssembly('@THAT')
        self.writeAssembly('M=D\n')

        self.writeAssembly('@R13')
        self.writeAssembly('AM=M-1')
        self.writeAssembly('D=M')
        self.writeAssembly('@THIS')
        self.writeAssembly('M=D\n')

        self.writeAssembly('@R13')
        self.writeAssembly('AM=M-1')
        self.writeAssembly('D=M')
        self.writeAssembly('@ARG')
        self.writeAssembly('M=D\n')

        self.writeAssembly('@R13')
        self.writeAssembly('A=M-1')
        self.writeAssembly('D=M')
        self.writeAssembly('@LCL')
        self.writeAssembly('M=D\n')

        self.writeAssembly('@R14')
        self.writeAssembly('A=M')
        self.writeAssembly('0;JMP\n')
